<div class="row">
    <h1>WPROWADŹ NOWE PRACE, STAWKI, GRUPY</h1>
</div>
<div class="row">
    <form>
        <div class="col-sm">
            <div class="form-group row">
                <label for="typ_prac" class="col-sm-2 col-form-label">Typ prac</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="typ_prac" id="typ_prac">
                </div>
            </div>
            <div class="form-group row">
               <label for="opis_prac" class="col-sm-2 col-form-label">Opis prac</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="opis_prac" id="opis_prac">
               </div>
            </div>
            <div class="form-group row">
               <label for="pstawka1" class="col-sm-2 col-form-label">Pstawka gr. 1</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="pstawka1" id="pstawka1">
               </div>
            </div>
            <div class="form-group row">
               <label for="pstawka2" class="col-sm-2 col-form-label">Pstawka gr. 2</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="pstawka2" id="pstawka2">
               </div>
            </div>
            <div class="form-group row">
               <label for="pstawka3" class="col-sm-2 col-form-label">Pstawka gr. 3</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="pstawka3" id="pstawka3">
               </div>
            </div>
            <div class="form-group row">
               <label for="kgrupa1" class="col-sm-2 col-form-label">Kgrupa 1</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="kgrupa1" id="kgrupa1">
               </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="form-group row">
               <label for="kgrupa2" class="col-sm-2 col-form-label">Kgrupa 2</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="kgrupa2" id="kgrupa2">
               </div>
            </div>
            <div class="form-group row">
                <label for="vat1" class="col-sm-2 col-form-label">VAT 1</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="vat1" id="vat1">
                </div>
            </div>
            <div class="form-group row">
                <label for="vat2" class="col-sm-2 col-form-label">VAT 2</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="vat2" id="vat2">
                </div>
            </div>
            <div class="form-group row">
                <label for="vat3" class="col-sm-2 col-form-label">VAT 3</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="vat3" id="vat3">
                </div>
            </div>
            <div class="form-group row">
                <label for="uwagi" class="col-sm-2 col-form-label">Uwagi</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="uwagi" id="uwagi">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Dodaj</button>
    </form>
</div>

