<div class="row">
    <h1>WPROWADŹ NOWY PROJEKT</h1>
</div>
<div class="row">
    <form>
        <div class="col-sm">
            <div class="form-group row">
                <label for="projekt" class="col-sm-2 col-form-label">Nr projektu</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="projekt" id="projekt">
                </div>
            </div>
            <div class="form-group row">
               <label for="firma" class="col-sm-2 col-form-label">Firma</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="firma" id="firma">
               </div>
            </div>
            <div class="form-group row">
               <label for="kgrupa" class="col-sm-2 col-form-label">Kgrupa</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="kgrupa" id="kgrupa">
               </div>
            </div>
            <div class="form-group row">
               <label for="pracownik" class="col-sm-2 col-form-label">Pracownik</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="pracownik" id="pracownik">
               </div>
            </div>
            <div class="form-group row">
               <label for="godzin" class="col-sm-2 col-form-label">Godzin</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="godzin" id="godzin">
               </div>
            </div>
            <div class="form-group row">
               <label for="pracownik2" class="col-sm-2 col-form-label">Pracownik 2</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="pracownik2" id="pracownik2">
               </div>
            </div>
            <div class="form-group row">
               <label for="godzin2" class="col-sm-2 col-form-label">Godzin</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="godzin2" id="godzin2">
               </div>
            </div>
            <div class="form-group row">
               <label for="pracownik3" class="col-sm-2 col-form-label">Pracownik 3</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="pracownik3" id="pracownik3">
               </div>
            </div>
            <div class="form-group row">
               <label for="godzin3" class="col-sm-2 col-form-label">Godzin</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="godzin3" id="godzin3">
               </div>
            </div>
            <div class="form-group row">
               <label for="pracownik4" class="col-sm-2 col-form-label">Pracownik 4</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="pracownik4" id="pracownik4">
               </div>
            </div>
            <div class="form-group row">
               <label for="godzin4" class="col-sm-2 col-form-label">Godzin</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="godzin4" id="godzin4">
               </div>
            </div>
            <div class="form-group row">
               <label for="godzin_razem" class="col-sm-2 col-form-label">Godzin razem</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="godzin_razem" id="godzin_razem">
               </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="form-group row">
                <label for="opis_materialu" class="col-sm-2 col-form-label">Opis materiału</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="opis_materialu" id="opis_materialu">
                </div>
            </div>
            <div class="form-group row">
                <label for="pojemnosc" class="col-sm-2 col-form-label">Pojemność</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="pojemnosc" id="pojemnosc">
                </div>
            </div>
            <div class="form-group row">
                <label for="kraj" class="col-sm-2 col-form-label">Kraj</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="kraj" id="kraj">
                </div>
            </div>
            <div class="form-group row">
                <label for="ilosc" class="col-sm-2 col-form-label">Ilość</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="ilosc" id="ilosc">
                </div>
            </div>
            <div class="form-group row">
                <label for="cena" class="col-sm-2 col-form-label">Cena</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="cena" id="cena">
                </div>
            </div>
            <div class="form-group row">
                <label for="koszt_materialu" class="col-sm-2 col-form-label">Koszt materiału</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="koszt_materialu" id="koszt_materialu">
                </div>
            </div>
            <div class="form-group row">
                <label for="koszt_pracy" class="col-sm-2 col-form-label">Koszt pracy</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="koszt_pracy" id="koszt_pracy">
                </div>
            </div>
            <div class="form-group row">
                <label for="koszt_ogolem" class="col-sm-2 col-form-label">Koszt ogółem</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="koszt_ogolem" id="koszt_ogolem">
                </div>
            </div>
            <div class="form-group row">
                <label for="typ_prac" class="col-sm-2 col-form-label">Typ prac</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="typ_prac" id="typ_prac">
                </div>
            </div>
            <div class="form-group row">
                <label for="opis_prac" class="col-sm-2 col-form-label">Opis</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="opis_prac" id="opis_prac">
                </div>
            </div>
            <div class="form-group row">
                <label for="rodzaj_materialu" class="col-sm-2 col-form-label">Rodzaj materiału</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="rodzaj_materialu" id="rodzaj_materialu">
                </div>
            </div>
            <div class="form-group row">
                <label for="nazwa_materialu" class="col-sm-2 col-form-label">Nazwa materiału</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="nazwa_materialu" id="nazwa_materialu">
                </div>
            </div>
            <div class="form-group row">
                <label for="uwagi" class="col-sm-2 col-form-label">Uwagi</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="uwagi" id="uwagi">
                </div>
            </div>
            <div class="form-group row">
                <label for="foto" class="col-sm-2 col-form-label">Foto</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="foto" id="foto">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Dodaj</button>
    </form>
</div>
