<div class="row">
    <h1>WPROWADŹ NOWE PRACE, STAWKI, GRUPY</h1>
</div>
<div class="row">
    <form>
        <div class="col-sm">
            <div class="form-group row">
                <label for="typ_prac" class="col-sm-2 col-form-label">Typ prac</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="typ_prac" id="typ_prac">
                </div>
            </div>
            <div class="form-group row">
               <label for="firma" class="col-sm-2 col-form-label">Firma</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="firma" id="firma">
               </div>
            </div>
            <div class="form-group row">
               <label for="rodzaj_materialu" class="col-sm-2 col-form-label">Rodzaj materiału</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="rodzaj_materialu" id="rodzaj_materialu">
               </div>
            </div>
            <div class="form-group row">
               <label for="nazwa" class="col-sm-2 col-form-label">Nazwa</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="nazwa" id="nazwa">
               </div>
            </div>
            <div class="form-group row">
               <label for="opis_materialu" class="col-sm-2 col-form-label">Opis materiału</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="opis_materialu" id="opis_materialu">
               </div>
            </div>
            <div class="form-group row">
               <label for="pojemnosc" class="col-sm-2 col-form-label">Pojemność</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="pojemnosc" id="pojemnosc">
               </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="form-group row">
               <label for="ilosc" class="col-sm-2 col-form-label">Ilość</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="ilosc" id="ilosc">
               </div>
            </div>
            <div class="form-group row">
                <label for="cena" class="col-sm-2 col-form-label">Cena</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="cena" id="cena">
                </div>
            </div>
            <div class="form-group row">
                <label for="foto" class="col-sm-2 col-form-label">Foto</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="foto" id="foto">
                </div>
            </div>
            <div class="form-group row">
                <label for="uwagi" class="col-sm-2 col-form-label">Uwagi</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="uwagi" id="uwagi">
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Dodaj</button>
    </form>
</div>


