<div class="row">
    <h1>WPROWADŹ NOWEGO DOSTAWCĘ</h1>
</div>
<div class="row">
    <form>
        <div class="col-sm">
            <div class="form-group row">
                <label for="firma" class="col-sm-2 col-form-label">Nazwa firmy</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="firma" id="firma">
                </div>
            </div>
            <div class="form-group row">
               <label for="stanowisko" class="col-sm-2 col-form-label">Stanowisko</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="stanowisko" id="stanowisko">
               </div>
            </div>
            <div class="form-group row">
               <label for="tytul" class="col-sm-2 col-form-label">Pan/Pani</label>
               <select id="tytul" class="form-control" name="tytul">
                   <option value="pan">Pan</option>
                   <option value="pani">Pani</option>
               </select>
            </div>
            <div class="form-group row">
               <label for="imie" class="col-sm-2 col-form-label">Imię</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="imie" id="imie">
               </div>
            </div>
            <div class="form-group row">
               <label for="nazwisko" class="col-sm-2 col-form-label">Nazwisko</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="nazwisko" id="nazwisko">
               </div>
            </div>
            <div class="form-group row">
               <label for="telefon" class="col-sm-2 col-form-label">Tel. stacjonarny</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="telefon" id="telefon">
               </div>
            </div>
            <div class="form-group row">
               <label for="mobile" class="col-sm-2 col-form-label">Tel. komórkowy</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="mobile" id="mobile">
               </div>
            </div>
            <div class="form-group row">
               <label for="email" class="col-sm-2 col-form-label">E-mail</label>
               <div class="col-sm-6">
                   <input type="email" class="form-control-plaintext" name="email" id="email">
               </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="form-group row">
                <label for="kraj" class="col-sm-2 col-form-label">Kraj</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control-plaintext" name="kraj" id="kraj">
                </div>
            </div>
            <div class="form-group row">
               <label for="wojewodztwo" class="col-sm-2 col-form-label">Województwo</label>
                <select id="wojewodztwo" class="form-control" name="wojewodztwo">
                    <option value="dolnośląskie">dolnośląskie</option>
                    <option value="kujawsko-pomorskie">kujawsko-pomorskie</option>
                    <option value="lubelskie">lubelskie</option>
                    <option value="lubuskie">lubuskie</option>
                    <option value="łódzkie">łódzkie</option>
                    <option value="małopolskie">małopolskie</option>
                    <option value="mazowieckie">mazowieckie</option>
                    <option value="opolskie">opolskie</option>
                    <option value="podkarpackie">podkarpackie</option>
                    <option value="podlaskie">podlaskie</option>
                    <option value="pomorskie">pomorskie</option>
                    <option value="śląskie">śląskie</option>
                    <option value="świętokrzyskie">świętokrzyskie</option>
                    <option value="warmińsko-mazurskie">warmińsko-mazurskie</option>
                    <option value="wielkopolskie">wielkopolskie</option>
                    <option value="zachodniopomorskie">zachodniopomorskie</option>
                </select>
            </div>
            <div class="form-group row">
               <label for="miasto" class="col-sm-2 col-form-label">Miasto</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="miasto" id="miasto">
               </div>
            </div>
            <div class="form-group row">
               <label for="ulica" class="col-sm-2 col-form-label">Ulica</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="ulica" id="ulica">
               </div>
            </div>
            <div class="form-group row">
               <label for="nr_lokalu" class="col-sm-2 col-form-label">Nr lokalu</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="nr_lokalu" id="nr_lokalu">
               </div>
            </div>
            <div class="form-group row">
               <label for="kgrupa" class="col-sm-2 col-form-label">Kgrupa</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="kgrupa" id="kgrupa">
               </div>
            </div>
            <div class="form-group row">
               <label for="foto" class="col-sm-2 col-form-label">Foto</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="foto" id="foto">
               </div>
            </div>
            <div class="form-group row">
               <label for="uwagi" class="col-sm-2 col-form-label">Uwagi</label>
               <div class="col-sm-6">
                   <input type="text" class="form-control-plaintext" name="uwagi" id="uwagi">
               </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Dodaj</button>
    </form>
</div>
